/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ufal.ic.rbs.view;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.AbstractAction;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Abigail Musa Gindaus
 */
public class FirstWindow extends javax.swing.JFrame {

    /**
     * Creates new form FirstWindow
     */
    public FirstWindow() {
        initComponents();
        alteration();
        setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAdministrator = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblAddproducts = new javax.swing.JLabel();
        lblUpdateproducts = new javax.swing.JLabel();
        lblManageproducts = new javax.swing.JLabel();
        lblOrderproducts = new javax.swing.JLabel();
        lblBilling = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Welcome To Your Restaurant Billing System", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria Math", 1, 14))); // NOI18N

        lblAdministrator.setText("Administrator");
        lblAdministrator.setName(""); // NOI18N

        jLabel2.setText("Customer");

        lblAddproducts.setText("Add products");

        lblUpdateproducts.setText(" Update products");

        lblManageproducts.setText("Manage products");

        lblOrderproducts.setText("Order products");

        lblBilling.setText("Billing");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAdministrator, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddproducts)
                    .addComponent(lblUpdateproducts)
                    .addComponent(lblManageproducts))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(107, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOrderproducts)
                            .addComponent(lblBilling))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdministrator, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddproducts)
                    .addComponent(lblOrderproducts))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpdateproducts)
                    .addComponent(lblBilling, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblManageproducts)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        btnExit.setText("Exit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btnExit))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void alteration(){
    
//        lblAddproducts.addMouseListener(new Behaviour(lblAddproducts, new ProductWindow()));
//        lblBilling.addMouseListener(new Behaviour(lblBilling, new BillWindow()));
//        lblManageproducts.addMouseListener(new Behaviour(lblManageproducts, new ManageWindow()));
//        lblOrderproducts.addMouseListener(new Behaviour(lblOrderproducts, new ItemWindow()));
//        lblUpdateproducts.addMouseListener(new Behaviour(lblUpdateproducts, new ProductWindow()));
        /*lblAddproducts.addMouseListener(new MouseListener() {
         @Override
            public void mouseClicked(MouseEvent me) {
                JOptionPane.showMessageDialog(null, "wow");
            }

            @Override
            public void mousePressed(MouseEvent me) {}

            @Override
            public void mouseReleased(MouseEvent me) {}

            @Override
            public void mouseEntered(MouseEvent me) {
                lblAddproducts.setForeground(Color.red);
            }

            @Override
            public void mouseExited(MouseEvent me) {
                lblAddproducts.setForeground(Color.black);
            }
        });*/
         
         
    }
    /**
     * @param args the command line arguments
     */
    class Behaviour extends MouseAdapter{
        JLabel label;
        JFrame f;
        public Behaviour(JLabel label, JFrame f) {
            this.label = label;
            this.f = f;
        }
         @Override
            public void mouseClicked(MouseEvent me) {
                f.setLocationRelativeTo(null);
                f.setVisible(true);
            }

            @Override
            public void mouseEntered(MouseEvent me) {
                label.setForeground(Color.red);
            }

            @Override
            public void mouseExited(MouseEvent me) {
                label.setForeground(Color.black);
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAddproducts;
    private javax.swing.JLabel lblAdministrator;
    private javax.swing.JLabel lblBilling;
    private javax.swing.JLabel lblManageproducts;
    private javax.swing.JLabel lblOrderproducts;
    private javax.swing.JLabel lblUpdateproducts;
    // End of variables declaration//GEN-END:variables

    class HyperlinkAction extends AbstractAction{

        @Override
        public void actionPerformed(ActionEvent ae) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
        public HyperlinkAction(String desc,String hover, Integer me){
            super(desc);
            putValue(SHORT_DESCRIPTION,hover);
            putValue(MNEMONIC_KEY, me);
        }
        
    
    }
    
    
    
}
